import type { MenuItem } from "./public/website/menu";
import type { Appearance, SiteBlockDefaults } from "./appearance";
import type { Catalogue } from "./public/storefront/contracts";
// Generated by scripts/generate-types.ts.
export type Block =
  | { id: string; type: "accordion"; props: { "heading": string; "cards": ({ "id": string; "title": string; "text": string; "image": string; "mediaId"?: string | undefined; "alt": string; "href": string; })[]; "allowMultiple": boolean; "openFirst": boolean; }; appearance?: Appearance; configured?: string[]; children?: Block[]; }
  | { id: string; type: "booking"; props: { "heading": string; "termsUrl": string; }; appearance?: Appearance; configured?: string[]; children?: Block[]; }
  | { id: string; type: "cart"; props: { "heading": string; "termsUrl": string; "layout": "full" | "summary" | "drawer"; }; appearance?: Appearance; configured?: string[]; children?: Block[]; }
  | { id: string; type: "catalogue"; props: { "heading": string; "cards": ({ "id": string; "title": string; "text": string; "image": string; "mediaId"?: string | undefined; "alt": string; "href": string; })[]; "columns": number; "layout": "grid" | "list"; "showImages": boolean; "showDescriptions": boolean; "source": "products" | "services" | "menus" | "classes" | "rental-offer" | "membership-offer"; "href": string; "search": string; "sort": "name" | "name-desc" | "price" | "price-desc" | "start"; "limit": number; "contentTypeId": string; "contentId"?: string | undefined; "fields": { "title": string; "text": string; "image": string; "href": string; }; "upcomingOnly": boolean; "showControls": boolean; "showPrices": boolean; "action": "auto" | "cart" | "select" | "enquiry" | "none"; "actionHref": string; }; appearance?: Appearance; configured?: string[]; children?: Block[]; }
  | { id: string; type: "classes"; props: { "heading": string; "termsUrl": string; }; appearance?: Appearance; configured?: string[]; children?: Block[]; }
  | { id: string; type: "component"; props: { "heading": string; "componentId"?: string | undefined; "configuration": Record<string, unknown>; }; appearance?: Appearance; configured?: string[]; children?: Block[]; }
  | { id: string; type: "content"; props: { "heading": string; "html": string; }; appearance?: Appearance; configured?: string[]; children?: Block[]; }
  | { id: string; type: "customer-account"; props: { "heading": string; }; appearance?: Appearance; configured?: string[]; children?: Block[]; }
  | { id: string; type: "enquiry"; props: { "heading": string; "termsUrl": string; "subjectLabel": string; "detailsLabel": string; "detailsPlaceholder": string; "submitLabel": string; "staged": boolean; "serviceFirst": boolean; "source": "none" | "services"; }; appearance?: Appearance; configured?: string[]; children?: Block[]; }
  | { id: string; type: "form"; props: { "heading": string; "formId"?: string | undefined; }; appearance?: Appearance; configured?: string[]; children?: Block[]; }
  | { id: string; type: "gallery"; props: { "heading": string; "cards": ({ "id": string; "title": string; "text": string; "image": string; "mediaId"?: string | undefined; "alt": string; "href": string; })[]; "columns": number; "layout": "grid" | "list"; "showImages": boolean; "showDescriptions": boolean; "presentation": "grid" | "slideshow"; }; appearance?: Appearance; configured?: string[]; children?: Block[]; }
  | { id: string; type: "grid"; props: { "heading": string; "cards": ({ "id": string; "title": string; "text": string; "image": string; "mediaId"?: string | undefined; "alt": string; "href": string; })[]; "columns": number; "layout": "grid" | "list"; "showImages": boolean; "showDescriptions": boolean; }; appearance?: Appearance; configured?: string[]; children?: Block[]; }
  | { id: string; type: "hero"; props: { "heading": string; "eyebrow": string; "text": string; "src": string; "mediaId"?: string | undefined; "alt": string; "caption": string; "primaryLabel": string; "primaryHref": string; "secondaryLabel": string; "secondaryHref": string; "layout": "split" | "wide" | "stack"; "mediaSide": "left" | "right"; }; appearance?: Appearance; configured?: string[]; children?: Block[]; }
  | { id: string; type: "html"; props: { "heading": string; "html": string; }; appearance?: Appearance; configured?: string[]; children?: Block[]; }
  | { id: string; type: "image"; props: { "heading": string; "src": string; "mediaId"?: string | undefined; "alt": string; "caption": string; "href": string; "showCaption": boolean; }; appearance?: Appearance; configured?: string[]; children?: Block[]; }
  | { id: string; type: "membership"; props: { "heading": string; "termsUrl": string; }; appearance?: Appearance; configured?: string[]; children?: Block[]; }
  | { id: string; type: "menu"; props: { "heading": string; "menuItems": MenuItem[]; "orientation": "horizontal" | "vertical"; }; appearance?: Appearance; configured?: string[]; children?: Block[]; }
  | { id: string; type: "page-content"; props: { "heading": string; "showHeading": boolean; }; appearance?: Appearance; configured?: string[]; children?: Block[]; }
  | { id: string; type: "preorder"; props: { "heading": string; "termsUrl": string; "cards": ({ "id": string; "title": string; "text": string; "image": string; "mediaId"?: string | undefined; "alt": string; "href": string; })[]; "presentation": "select" | "menu" | "boxes"; }; appearance?: Appearance; configured?: string[]; children?: Block[]; }
  | { id: string; type: "quote-acceptance"; props: { "heading": string; "quoteId": string; }; appearance?: Appearance; configured?: string[]; children?: Block[]; }
  | { id: string; type: "rental"; props: { "heading": string; "termsUrl": string; }; appearance?: Appearance; configured?: string[]; children?: Block[]; }
  | { id: string; type: "request-status"; props: { "heading": string; "id": string; }; appearance?: Appearance; configured?: string[]; children?: Block[]; }
  | { id: string; type: "rich-text"; props: { "heading": string; "html": string; }; appearance?: Appearance; configured?: string[]; children?: Block[]; }
  | { id: string; type: "section"; props: { "heading": string; "role": "header" | "footer" | "section"; "showBranding": boolean; }; appearance?: Appearance; configured?: string[]; children?: Block[]; }
  | { id: string; type: "view"; props: { "heading": string; "cards": ({ "id": string; "title": string; "text": string; "image": string; "mediaId"?: string | undefined; "alt": string; "href": string; })[]; "columns": number; "layout": "grid" | "list"; "showImages": boolean; "showDescriptions": boolean; "source": "products" | "services" | "menus" | "classes" | "rental-offer" | "membership-offer"; "href": string; "search": string; "sort": "name" | "name-desc" | "price" | "price-desc"; "limit": number; "contentTypeId": string; "contentId"?: string | undefined; "fields": { "title": string; "text": string; "image": string; "href": string; }; }; appearance?: Appearance; configured?: string[]; children?: Block[]; };
export type PageDocument = {
  kind: "page";
  slug: string;
  templateId: string;
  layoutId: string;
  parentId: string | null;
  position: number;
  title: string;
  description: string;
  blocks: Block[];
  redirects: string[];
  schemaVersion: 2;
  id: string;
  name: string;
};
export type LayoutDocument = {
  kind: "layout";
  templateId: string;
  blocks: Block[];
  schemaVersion: 2;
  id: string;
  name: string;
};
export type AliasDocument = {
  kind: "alias";
  sourcePageId: string;
  slug: string;
  parentId: string | null;
  position: number;
  redirects: string[];
  schemaVersion: 2;
  id: string;
  name: string;
};
export type SiteDocument =
  | {
      kind: "page";
      slug: string;
      templateId: string;
      layoutId: string;
      parentId: string | null;
      position: number;
      title: string;
      description: string;
      blocks: Block[];
      redirects: string[];
      schemaVersion: 2;
      id: string;
      name: string;
    }
  | {
      kind: "layout";
      templateId: string;
      blocks: Block[];
      schemaVersion: 2;
      id: string;
      name: string;
    }
  | {
      kind: "alias";
      sourcePageId: string;
      slug: string;
      parentId: string | null;
      position: number;
      redirects: string[];
      schemaVersion: 2;
      id: string;
      name: string;
    }
  | {
      kind: "form";
      fields: {
        id: string;
        label: string;
        type:
          | "number"
          | "date"
          | "file"
          | "email"
          | "text"
          | "textarea"
          | "checkbox"
          | "select"
          | "radio"
          | "consent"
          | "tel";
        required: boolean;
        help: string;
        options: string[];
        file?:
          | {
              preset?:
                | "any"
                | "custom"
                | "images"
                | "documents"
                | "audio"
                | "video"
                | "images-and-documents"
                | undefined;
              extensions?: string[] | undefined;
              maxBytes?: number | undefined;
              maxFiles?: number | undefined;
            }
          | undefined;
      }[];
      submitLabel: string;
      successMessage: string;
      actions: {
        notifyStaff: string[];
        customer: boolean;
        enquiry: boolean;
        nameField: string;
        emailField: string;
        phoneField: string;
        messageField: string;
      };
      formLayout: "stacked" | "inline";
      floatingLabels: boolean;
      schemaVersion: 2;
      id: string;
      name: string;
    };
export type SiteEntry = {
  document: SiteDocument;
  published: SiteDocument | null;
  version: number;
  publishedVersion: number;
  updatedAt: number;
  needsPublication: boolean;
};
export type RegisteredBlock = {
  id: string;
  label: string;
  fields: {
    key: string;
    label: string;
    type: "number" | "text" | "textarea" | "checkbox" | "url";
  }[];
};
export type NavigationItem = {
  label: string;
  href: string;
  children?: NavigationItem[];
};
export type WebsiteRenderData = {
  blockDefaults?: SiteBlockDefaults;
  page: PageDocument;
  layout: LayoutDocument;
  documents: SiteDocument[];
  navigation: NavigationItem[];
  catalogue: Catalogue;
  preview?: boolean;
  editingDocumentId?: string;
  editingDocumentKind?: "page" | "layout";
};
