import { readdir, readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { z } from "zod";
const root = resolve(import.meta.dirname, "..");
type Schema = {
  type?: string | string[];
  enum?: unknown[];
  const?: unknown;
  properties?: Record<string, Schema>;
  required?: string[];
  items?: Schema;
  anyOf?: Schema[];
  additionalProperties?: boolean | Schema;
  $ref?: string;
};
function type(schema: Schema, property = ""): string {
  if (property === "menuItems") return "MenuItem[]";
  if (schema.const !== undefined) return JSON.stringify(schema.const);
  if (schema.enum)
    return schema.enum.map((value) => JSON.stringify(value)).join(" | ");
  if (schema.anyOf) return schema.anyOf.map((value) => type(value)).join(" | ");
  if (Array.isArray(schema.type))
    return schema.type
      .map((value) => type({ ...schema, type: value }))
      .join(" | ");
  if (schema.type === "array") return `(${type(schema.items ?? {})})[]`;
  if (schema.type === "object") {
    if (!schema.properties) return "Record<string, unknown>";
    return `{ ${Object.entries(schema.properties)
      .map(
        ([key, value]) =>
          `${JSON.stringify(key)}${schema.required?.includes(key) ? "" : "?"}: ${type(value, key)}${schema.required?.includes(key) ? "" : " | undefined"};`,
      )
      .join(" ")} }`;
  }
  if (schema.type === "integer" || schema.type === "number") return "number";
  if (["string", "boolean", "null"].includes(schema.type ?? ""))
    return schema.type!;
  return "unknown";
}
/** Generate the closed system-block union without making the SDK depend on
 * block implementation packages. Public extension authors use their manifest. */
export async function generateTypes() {
  const target = resolve(root, "packages/sdk/src/website-types.ts");
  const source = await readFile(target, "utf8");
  const members = [];
  for (const name of (await readdir(resolve(root, "packages")))
    .filter((name) => name !== "sdk")
    .sort()) {
    const { definition } = await import(
      resolve(root, "packages", name, "definition.ts")
    );
    members.push(
      `  | { id: string; type: ${JSON.stringify(name)}; props: ${type(z.toJSONSchema(definition.schema, { unrepresentable: "any" }) as Schema)}; appearance?: Appearance; configured?: string[]; children?: Block[]; }`,
    );
  }
  await writeFile(
    target,
    source.slice(
      0,
      source.indexOf("// Generated by scripts/generate-types.ts."),
    ) +
      "// Generated by scripts/generate-types.ts.\nexport type Block =\n" +
      members.join("\n") +
      ";\n" +
      source.slice(source.indexOf("export type PageDocument")),
  );
}
if (import.meta.main) await generateTypes();
